### ISSUE TITLE
Nu block (section 4.3.2) 

### ISSUE THREAD

**Issue by ghost** [NuclearData/ACEFormat#12]
I checked multiple times but I think there is an error in the NU block description.

For the NU block, there are three possibilities : 
- No NU block `JXS(2) = 0` => OK
- Either prompt or total nu is given : in this case the documentation states `JXS(2) > 0` but I think it should be `JXS(2) != 0 and XSS(JXS(2)) > 0`
- Both prompt and total are given : in this case the documentation states `JXS(2) < 0` but i think it should be `JXS(2) != 0 and XSS(JXS(2)) < 0`

In the last case, if we follow the actual format specification KNU index can be negative for the prompt/total array ...

> Both prompt and total ν are given. (JXS(2) < 0).
– The prompt NU array begins at XSS(KNU) where KNU=JXS(2) + 1.
– The total NU array begins at XSS(KNU) where KNU = JXS(2) + ABS(XSS(JXS(2)))+1. 

I can submit a PR, just wanted to check with you if i did not misunderstand what I found in nuclear data base(s) ...
Thank you.

**Comment by paulromano** [comment]
I concur with this -- it looks like what we have currently is different than what appears in the MCNP5 manual vol III, which matches what @johannmartinet described. Clearly `JXS(2) < 0` doesn't makes sense because it is used as an index in `XSS`.

**Comment by johannmartinet** [comment]
@paulromano Thanks for your comment. 

I extracted the relevant part from MCNP5 manual vol III : 

> 1. JXS(2)=0
> no NU Block
>  2. XSS(JXS(2))>0
> either prompt ν or total ν is given. The NU array begins at
> location XSS(KNU) where KNU=JXS(2).
>  3. XSS(JXS(2))<0
> both prompt ν and total ν are given. The prompt NU Array
> begins at XSS(KNU) where KNU=JXS(2)+1; the total NU
> array begins at XSS(KNU), where
> KNU=JXS(2)+ABS(XSS(JXS(2)))+1.

**Comment by jlconlin** [comment]
@johannmartinet Thanks for raising this issue. I agree that it isn't very clear. Please submit a Pull Request and we can take a look.
